# Generated by Django 5.2.15 on 2026-07-03 22:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=2)),
                ('latitude', models.DecimalField(decimal_places=4, max_digits=6)),
                ('longitude', models.DecimalField(decimal_places=4, max_digits=7)),
            ],
            options={
                'ordering': ['country', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DailyForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forecast_date', models.DateField()),
                ('horizon', models.CharField(choices=[('short', 'Short (16 days)'), ('mid', 'Mid (6 weeks)'), ('long', 'Long (7 months)'), ('historical', 'Historical (ERA5)')], max_length=12)),
                ('fetched_at', models.DateTimeField(auto_now=True)),
                ('temperature_max', models.FloatField(blank=True, null=True)),
                ('temperature_min', models.FloatField(blank=True, null=True)),
                ('precipitation_sum', models.FloatField(blank=True, null=True)),
                ('wind_speed_max', models.FloatField(blank=True, null=True)),
                ('precipitation_prob_max', models.IntegerField(blank=True, null=True)),
                ('weather_code', models.IntegerField(blank=True, null=True)),
                ('point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forecasts', to='ingest.weatherpoint')),
            ],
            options={
                'ordering': ['forecast_date'],
                'unique_together': {('point', 'forecast_date', 'horizon')},
            },
        ),
    ]
