# Generated by Django 5.2.15 on 2026-07-04 20:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalActual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('temp_min', models.FloatField(blank=True, null=True)),
                ('temp_max', models.FloatField(blank=True, null=True)),
                ('precip_mm', models.FloatField(blank=True, null=True)),
                ('wind_kmh', models.FloatField(blank=True, null=True)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='MediumLongRangeForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_date', models.DateField()),
                ('issued_at', models.DateTimeField()),
                ('horizon', models.CharField(choices=[('ec46', 'EC46 (6 týdnů)'), ('seas5', 'SEAS5 (7 měsíců)')], max_length=10)),
                ('temp_mean', models.FloatField(blank=True, null=True)),
                ('temp_anomaly', models.FloatField(blank=True, null=True)),
                ('precip_probability', models.FloatField(blank=True, null=True)),
                ('source_model', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'ordering': ['target_date', '-issued_at'],
            },
        ),
        migrations.CreateModel(
            name='PollenRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('issued_at', models.DateTimeField()),
                ('birch', models.FloatField(blank=True, null=True)),
                ('grass', models.FloatField(blank=True, null=True)),
                ('ragweed', models.FloatField(blank=True, null=True)),
                ('alder', models.FloatField(blank=True, null=True)),
                ('mugwort', models.FloatField(blank=True, null=True)),
                ('aqi_european', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['date', '-issued_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='dailyforecast',
            options={'ordering': ['forecast_date', '-issued_at']},
        ),
        migrations.AlterUniqueTogether(
            name='dailyforecast',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='dailyforecast',
            name='issued_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='dailyforecast',
            index=models.Index(fields=['point', 'forecast_date', 'horizon'], name='ingest_dail_point_i_00836f_idx'),
        ),
        migrations.AddIndex(
            model_name='dailyforecast',
            index=models.Index(fields=['issued_at'], name='ingest_dail_issued__905fdd_idx'),
        ),
        migrations.AddField(
            model_name='historicalactual',
            name='point',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historical_actuals', to='ingest.weatherpoint'),
        ),
        migrations.AddField(
            model_name='mediumlongrangeforecast',
            name='point',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medium_long_forecasts', to='ingest.weatherpoint'),
        ),
        migrations.AddField(
            model_name='pollenrecord',
            name='point',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pollen_records', to='ingest.weatherpoint'),
        ),
        migrations.AlterUniqueTogether(
            name='historicalactual',
            unique_together={('point', 'date')},
        ),
        migrations.AddIndex(
            model_name='mediumlongrangeforecast',
            index=models.Index(fields=['point', 'target_date', 'horizon', 'issued_at'], name='ingest_medi_point_i_f74dbd_idx'),
        ),
        migrations.AddIndex(
            model_name='pollenrecord',
            index=models.Index(fields=['point', 'date', 'issued_at'], name='ingest_poll_point_i_815d1a_idx'),
        ),
    ]
