# Generated by Django 5.2.15 on 2026-07-12 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingest', '0002_phase4_revision_tracking'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='historicalactual',
            index=models.Index(fields=['point', 'date'], name='ingest_hist_point_i_4bf92d_idx'),
        ),
        migrations.AddIndex(
            model_name='historicalactual',
            index=models.Index(fields=['date'], name='ingest_hist_date_842472_idx'),
        ),
        migrations.AddIndex(
            model_name='weatherpoint',
            index=models.Index(fields=['country'], name='ingest_weat_country_f7a3c2_idx'),
        ),
    ]
