# Generated by Django 5.2.15 on 2026-07-15 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingest', '0003_historicalactual_ingest_hist_point_i_4bf92d_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivedForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valid_date', models.DateField()),
                ('lead_days', models.PositiveSmallIntegerField()),
                ('temp_max', models.FloatField(blank=True, null=True)),
                ('temp_min', models.FloatField(blank=True, null=True)),
                ('precip_mm', models.FloatField(blank=True, null=True)),
                ('source', models.CharField(choices=[('prev', 'Previous runs (1–7 dní)'), ('single', 'Single runs (8–15 dní)')], max_length=6)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archived_forecasts', to='ingest.weatherpoint')),
            ],
            options={
                'ordering': ['valid_date', 'lead_days'],
                'indexes': [models.Index(fields=['point', 'valid_date'], name='ingest_arch_point_i_0e1c2f_idx')],
                'constraints': [models.UniqueConstraint(fields=('point', 'valid_date', 'lead_days'), name='uniq_archived_forecast')],
            },
        ),
    ]
