# Generated by Django 5.2.15 on 2026-07-16 09:24

from django.db import migrations, models

# Same assignment as seed_points.py — keyed by (name, country) because pks
# differ between environments. Kept literal here so the migration stays
# self-contained even if the seed command changes later.
MACRO_BY_NAME = {
    ("Praha", "CZ"): "cechy",
    ("Středočeský", "CZ"): "cechy",
    ("České Budějovice", "CZ"): "cechy",
    ("Plzeň", "CZ"): "cechy",
    ("Karlovy Vary", "CZ"): "cechy",
    ("Ústí nad Labem", "CZ"): "cechy",
    ("Liberec", "CZ"): "cechy",
    ("Hradec Králové", "CZ"): "cechy",
    ("Pardubice", "CZ"): "cechy",
    ("Jihlava", "CZ"): "morava",
    ("Brno", "CZ"): "morava",
    ("Olomouc", "CZ"): "morava",
    ("Zlín", "CZ"): "morava",
    ("Ostrava", "CZ"): "morava",
    ("Bratislava", "SK"): "zapadne",
    ("Trnava", "SK"): "zapadne",
    ("Trenčín", "SK"): "zapadne",
    ("Nitra", "SK"): "zapadne",
    ("Žilina", "SK"): "stredne",
    ("Banská Bystrica", "SK"): "stredne",
    ("Prešov", "SK"): "vychodne",
    ("Košice", "SK"): "vychodne",
}


def populate_macro_region(apps, schema_editor):
    WeatherPoint = apps.get_model("ingest", "WeatherPoint")
    for point in WeatherPoint.objects.all():
        macro = MACRO_BY_NAME.get((point.name, point.country))
        if macro:
            point.macro_region = macro
            point.save(update_fields=["macro_region"])


class Migration(migrations.Migration):

    dependencies = [
        ('ingest', '0003_historicalactual_ingest_hist_point_i_4bf92d_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='weatherpoint',
            name='macro_region',
            field=models.CharField(blank=True, choices=[('cechy', 'Čechy'), ('morava', 'Morava'), ('zapadne', 'Západné Slovensko'), ('stredne', 'Stredné Slovensko'), ('vychodne', 'Východné Slovensko')], default='', max_length=10),
        ),
        migrations.AddIndex(
            model_name='weatherpoint',
            index=models.Index(fields=['macro_region'], name='ingest_weat_macro_r_fc9ae4_idx'),
        ),
        migrations.RunPython(populate_macro_region, migrations.RunPython.noop),
    ]
