# Generated by Django 5.2.15 on 2026-07-09 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_phase4_note_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='country',
            field=models.CharField(choices=[('cz', 'ČR'), ('sk', 'SR'), ('both', 'ČR + SR')], default='both', max_length=5),
        ),
        migrations.AddField(
            model_name='note',
            name='horizon',
            field=models.CharField(choices=[('short', 'Krátkodobá'), ('mid', 'Střednědobá'), ('long', 'Dlouhodobá')], default='short', max_length=6),
        ),
    ]
