# Generated by Django 5.2.15 on 2026-07-14 19:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_note_is_hidden'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoriePin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_pinned', models.BooleanField(default=False)),
                ('is_hidden', models.BooleanField(default=False)),
                ('sel', models.CharField(max_length=10)),
                ('od', models.CharField(max_length=10)),
                ('do', models.CharField(max_length=10)),
                ('roky', models.PositiveSmallIntegerField(default=5)),
                ('metric', models.CharField(choices=[('t', 'Teplota (°C)'), ('p', 'Srážky (mm)')], default='t', max_length=1)),
                ('show_in_feed', models.BooleanField(default=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historie_pins', to=settings.AUTH_USER_MODEL)),
                ('feed_note', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historie_pin', to='notes.note')),
            ],
            options={
                'ordering': ['-is_pinned', '-created_at'],
                'indexes': [models.Index(fields=['sel', 'metric'], name='notes_histo_sel_34a925_idx')],
            },
        ),
    ]
